version: '3.2'
services:
    alarm-server:
        image: lnlscon/alarm-server:latest
        hostname: alarm-server
        networks:
            - alarm-network
        dns:
            - 10.0.0.71
            - 10.0.0.72
        depends_on:
            - alarm-server-postgres-db
            - alarm-server-activemq
        env_file:
            - /home/srv1/repository/docker-alarm-composed/lnls-beast-server.env
        deploy:
            resources:
              limits:
                cpus: "2"
                memory: 1024M

    alarm-server-postgres-db:
        image: lnlscon/alarm-postgres-db:latest
        hostname: alarm-server-postgres-db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=lnls_alarm_user
            - POSTGRES_PASSWORD=controle
            - POSTGRES_DB=lnls_alarms
            - PGDATA=/var/lib/postgresql/data/alarm-db
        networks:
            - alarm-network
        dns:
            - 10.0.0.71
            - 10.0.0.72
        volumes:
            - /storage/beast/db/:/var/lib/postgresql/data/alarm-db
        deploy:
            resources:
              limits:
                cpus: "2"
                memory: 1024M

    alarm-server-activemq:
        image: lnlscon/alarm-server-activemq:latest
        hostname: alarm-server-activemq
        ports:
            - "61616:61616"
        dns:
            - 10.0.0.71
            - 10.0.0.72
        networks:
            - alarm-network
        deploy:
            resources:
              limits:
                cpus: "2"
                memory: 1024M


networks:
    alarm-network:
        driver: overlay
        ipam:
            config:
                - subnet: 192.168.4.0/24
    
