apiVersion: v1
kind: Service
metadata:
  name: beast-alarm-postgres-db-service
spec:
  clusterIP: 192.168.4.3
  selector:
    app : beast-alarm-postgres-db
  ports:
  - name: beast-alarm-postgres-db-port
    port: 5432
    targetPort: 5432
    nodePort: 32435
  type: NodePort
