apiVersion: v1
kind: Service
metadata:
  name: beast-alarm-activemq-service
spec:
  clusterIP: 192.168.4.4
  selector:
    app : beast-alarm-activemq
  ports:
  - name: beast-alarm-activemq-port
    port: 61616
    targetPort: 61616
    nodePort: 31616
  type: NodePort
